---
- name: Install nginx
  apt: name=nginx state=present

- name: Remove nginx default configuration file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy nginx configuration for wordpress
  template:
    src: wordpress.nginx.conf
    dest: /etc/nginx/sites-available/
    mode: 0644

- name: Create wordpress nginx symlink
  file:
    src: /etc/nginx/sites-available/wordpress.nginx.conf
    dest: /etc/nginx/sites-enabled/wordpress.nginx.conf
    state: link
  # notify: restart nginx

- name: Start Nginx Service
  service: name=nginx state=started enabled=yes

#- name: Copy nginx configuration for wordpress
#  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#  notify: restart nginx
